language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "grace-shopper";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: grace-shopper-lags
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: c5Xa3gBBI8HkxQdHGuFEYeeJVRfYJWUjXdEZc+sMiE3+xYbH4dRw15nIU0FUzs9NVOud8e0Eh7kdVfW5ht2j4K7Iaa6asJS+M40XU8x1uR7iT/Pb9F7o0Mhlr3MIT6qYdREbA51baBqdTrZNTQISfRNm0r+cMpHeWrPoCG0tBuW+bNYP9agKWesqKQSs0MYZ0LECeHqGFNRoDPMafmntGb+aHO7j9ktmCXTdz0qLe7vCi30M2W0LXOCUKDV2m48rMe7uO4nXBifGO8qhmg13j/98d4ST8eECwckwxizrGftC+UmHIYSy1av+CTo/apwF/70oXS73RsBuBjWOVE1ab8vWqj27NI99QxLp4RPg/ozI7K+oLI1kTTlCVKCkYTCKDW6IgCWMUQ3DBHUIwbkt+hTWbVEuq+K3NsceHpfHnlcyE5pOxWfBbciEaMtOQ0X7Pmx28xYTGb8sbUxs5IRxynybivWTH1XyxQFUTrgYcAoL4PCA4aufYZ9rXY5aQa6hx41XlnbsggyC+LuEwp1kQVFsgxtp/WrFvuVBt/9UC6C0JlEsXDawgIaPWSYE2emJhuPqZsZPcOCuZmh9mmf+ALCgcXK1ThOyqAVCKMunLAdowHynW4aMzSfa0kKrthOB7GvIcbhIg43cIffx01QNYTueGALBwQuHIkRiDWO3Ilw=
